name: Playwright Accessibility Tests
on:
  workflow_dispatch
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run Playwright accessibility tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: accessibility-reports-desktop
          path: accessibilityReports-AccessibilityDesktop
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: accessibility-reports-mobile
          path: accessibilityReports-AccessibilityMobile
          retention-days: 30
